#            _       __                                             _
#     ____  (_)___  / /______ ___  ____ _____  ____  ___  _________( )
#    / __ \/ / __ \/ //_/ __ `__ \/ __ `/ __ \/ __ \/ _ \/ ___/ ___//
#   / /_/ / / / / / ,< / / / / / / /_/ / / / / / / /  __/ /  (__  )
#  / .___/_/_/ /_/_/|_/_/ /_/_/_/\__,_/_/ /_/_/_/_/\___/_/  /____/ ____
# /_// /_  __  ______  _____/ /___ _____  ____/ /_________  ____  / __/
#   / __ \/ / / / __ \/ ___/ / __ `/ __ \/ __  // ___/ __ \/ __ \/ /_
#  / / / / /_/ / /_/ / /  / / /_/ / / / / /_/ // /__/ /_/ / / / / __/
# /_/ /_/\__, / .___/_/  /_/\__,_/_/ /_/\__,_(_)___/\____/_/ /_/_/
#       /____/_/

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/defaultPrograms.conf
source = ~/.config/hypr/autoStart.conf
source = ~/.config/hypr/environmentVariables.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/workspacesWindows.conf
source = ~/.config/hypr/macchiato.conf
